### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by kopach** [urish/typewiz-webpack-demo#2]
Is this demo project still working? I've tried few times. It does show found types on the page, however it doesn't produce `collected-types.json` file for me.

**Comment by urish** [comment]
Just tested it locally and it seems to work - and `collected-type.json` is produced successfully.

Do you use `yarn` or `npm`? Also, which operating system do you have?

Can you check the network panel to see if the frontend is submitting requests to the webpack dev server? It should be posting the types to `/__typewiz_report` every second or so.

**Comment by kopach** [comment]
I've tested it with both `yarn` and `npm`. My OS is macOS High Sierra. Frontend is submitting requests to the webpack dev server correctly, but `collected-type.json` isn't produced anyway.

node --version
v8.9.1
npm --version
5.8.0
yarn --version
1.6.0

**Comment by kopach** [comment]
I think, it may be an issue with dependencies versions. Could you produce `npm-shrinkwrap.json` file so I could try to reinstall everything with just npm again?

**Comment by urish** [comment]
If frontend submits the requests the the dev server correctly, I'd try to put a debug print [here](https://github.com/urish/typewiz-webpack-demo/blob/d9ab744bf238c413ba7850aaf18de05e7bded97f/webpack.config.js#L31
) to see if the middleware is actually being called, I'd suggest to try to use there absolute path for `collected-types.json`, just to make sure it's written to the place you expect it too. I'd love to hear if it did the trick!

**Comment by kopach** [comment]
Ok, it actually does work for me. Sorry, it was my fault. 
Firstly I've tried `typewiz` on my current project and it didn't work as expected because I'm using angular-cli. I've managed to get types manually after all but still decided to check this demo project meanwhile. And here was the source of problem: I've been using `git status` in order to check if there are any changed files (the same way I used to do for my project :/). 

So, even though, this is my mistake, maybe you could remove `collected-types.json` from `.gitignore`. After all, this is demo project and I think it's better to highlight changes `collected-types.json` as much as possible to prevent further confusions :)

**Comment by urish** [comment]
Thanks for the update - good input about `.gitignore`, I followed your suggestion and remove `collected-types.json` from there.

When you say you got the types manually, did you do that by manually setting up TypeWiz or without TypeWiz at all?
